[phases.setup]
nixPkgs = ["nodejs-20_x", "yarn"]

[phases.build]
cmds = ["yarn install --immutable", "yarn prisma generate", "yarn build"]

[phases.start]
cmd = "yarn start"

[variables]
NODE_VERSION = "20"
